---

- name: "[INSTALL] - Install epel repo (CentOS/RedHat)"
  yum: 
    name: "epel-release"
    state: "installed"
  when:
    - ansible_os_family == "RedHat"

- name: "[INSTALL] - Enable epel repo (CentOS/RedHat)"
  ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: epel
    option: enabled
    value: 1
  when:
    - ansible_os_family == "RedHat"

- name: "[INSTALL] - Install scl repo (CentOS)"
  yum: 
    name: "centos-release-scl"
    state: "installed"
  when:
    - ansible_distribution == "CentOS"

- name: "[INSTALL] -  Required and recommended packages are installed. (Debian/Ubuntu)"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ nextcloud_websrv }}"
    - smbclient
    - "php{{ php_ver }}-gd"
    - "php{{ php_ver }}-ldap"
    - "php{{ php_ver }}-imap"
    - "php{{ php_ver }}-json"
    - "php{{ php_ver }}-curl"
    - "php{{ php_ver }}-intl"
  notify:
    - start http
  when:
    - ansible_os_family == "Debian"

- name: "[INSTALL] -  Required and recommended packages are installed. (CentOS/RedHat)"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ nextcloud_websrv }}"
    - samba-client
    - "rh-php{{ php_ver }}-php-gd"
    - "rh-php{{ php_ver }}-php-ldap"
    - "rh-php{{ php_ver }}-php-imap"
    - "rh-php{{ php_ver }}-php-json"
    - "rh-php{{ php_ver }}-php-curl"
    - "rh-php{{ php_ver }}-php-intl"
  notify:
    - start http
  when:
    - ansible_os_family == "RedHat"

- name: "[INSTALL] -  Apache Required package is installed."
  package:
    name: "libapache2-mod-php{{ php_ver }}"
    state: present
  when: nextcloud_websrv == "apache2"
  notify:
    - start http

- name: "[INSTALL] -  NGINX Required package is installed. (Debian/Ubuntu)"
  package:
    name: "php{{ php_ver }}-fpm"
    state: present
  when: 
    - nextcloud_websrv == "nginx"
    - ansible_os_family == "Debian"
  notify:
    - start http
    - start php-fpm

- name: "[INSTALL] -  NGINX Required package is installed. (CentOS/RedHat)"
  package:
    name: "rh-php{{ php_ver }}-php-fpm"
    state: present
  when: 
    - nextcloud_websrv == "nginx"
    - ansible_os_family == "RedHat"
  notify:
    - start http
    - start php-fpm-rh

- name: "[INSTALL] -  PHP extra Packages are installed."
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ php_pkg_spe }}"

- name: "Create /usr/bin/php link (Redhat/CentOS)"
  file:
    src: "/opt/rh/rh-php{{ php_ver }}/root/usr/bin/php"
    dest: "/usr/bin/php"
    state: "link"
  when:
    - ansible_os_family == "RedHat"

- name: "[INSTALL] -  APCu is installed."
  package:
    name: "{{ php_pkg_apcu }}"
    state: present
  when : ansible_distribution_release not in [ "trusty" ]

- block:
  # load APCu from backports as the default version for trusty is obsolete.
  - name: "[INSTALL] -  Configure trusty backports."
    apt_repository:
      repo: "deb http://fr.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse"
      state: present
      update_cache: yes

  - name: "[INSTALL] -  Install APCu from backports."
    package:
      name: "{{ php_pkg_apcu }}"
      state: present
      default_release: trusty-backports
  when: ansible_distribution_release == "trusty"



